// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type Mutation struct {
}

type NewMessage struct {
	Text string `json:"text"`
}

type Query struct {
}
